name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]
    paths-ignore:
      - "github-metrics.svg"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MJordanBecode
          filename: github-metrics.svg
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 10
          plugin_anilist_shuffle: yes

      - name: Commit and push metrics
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-metrics.svg
          git commit -m "Update github-metrics.svg - [skip ci]" || echo "No changes
          git push