name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MJordanBecode

          base: ""
          
          # AniList plugin for manga favorites and reading list
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 10
          plugin_anilist_shuffle: yes
