name: Metrics
on:
  # Exécution quotidienne
  schedule: [{cron: "0 0 * * *"}]
  # Exécution manuelle possible
  workflow_dispatch:
  # Exécution lors d'un push sur main/master
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Votre token GitHub
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options de base
          user: MJordanBecode  # Remplacez par votre nom d'utilisateur
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          
          # Plugin Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          
          # Autres plugins utiles
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_limit: 8