name: Achievements
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Désactiver les métriques de base
          base: ""
          
          # Activer uniquement le plugin Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact  # Affichage compact comme dans l'image
          plugin_achievements_threshold: C      # Afficher les achievements de rang C et supérieur
          plugin_achievements_secrets: yes      # Inclure les achievements secrets
          plugin_achievements_limit: 0          # 0 = pas de limite
          
          # Optionnel: si vous voulez afficher seulement certains achievements
          # plugin_achievements_only: >-
          #   polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          #   scripter, packager, explorer, infographile, manager
