name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options de base
          user: MJordanBecode
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          
          # Contrôle de la taille
          config_display: large  # Options: large, columns, regular
          config_padding: 0%     # Réduire les marges (0% à 10%)
          config_order: base.header, achievements, isocalendar, languages  # Contrôler l'ordre et inclure seulement ce que vous voulez
          
          # Achievements plugin (version plus compacte)
          plugin_achievements: yes
          plugin_achievements_display: compact  # "compact" au lieu de "detailed"
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 6  # Limiter le nombre d'achievements affichés
          
          # Autres plugins (plus compacts)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_limit: 6  # Réduire le nombre de langages