name: Metrics
on:
  schedule: [{ cron: "0 6 * * *" }]  # mise à jour quotidienne à 6h UTC
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MJordanBecode
          base: header, repositories
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
